### ISSUE TITLE
Why this tool isn't a tiny wrapper around vagga to run on mac os?

### ISSUE THREAD

**Issue by tailhook** [vmagamedov/pi#2]
I'll start with brief description of vagga (I know @vmagamedov already knows that but somebody visiting a page might not):

[Vagga](http://vagga.readthedocs.io/en/latest/) does very similar thing to what pi is supposed to do: it allows to build containers and run commands inside. It keeps list of commands in yaml config, including all advanced things like mounting volumes, building containers and so on, including the possibility to add a description for the command  :) (which make lacks for unknown reason)

The key difference is: pi uses docker as a containerization, but vagga doesn't, it implements containers using raw linux system calls. And that largely limits feature set of both utilities. Let me explain.

## Why Vagga Doesn't Use Docker?

There are two major reasons for this, that are relevant to this discussion:

1. We want security: `vagga test` in a gitlab-ci has access only to project dir (+ containers and cache), and doesn't run with elevated privileges (as a user that runs gitlab-ci-runner). While any tool around docker can `docker run --privileged`. [*]

2. We want IDE accessibility: python libraries of the container are in `.vagga/containername/usr/lib/python3.5/site-packages`. So you can just point IDE there. For docker you need some hacks to achieve this.

[*] To run docker securely on a shared server like gitlab-ci you need to set up a separate virtual machine for every project and use docker socket of that machine in docker run. And yes we need security in CI system because we deploy from it.

## How You Can Use Vagga on Mac OS?

Vagga runs in docker on linux perfectly fine. So should run in docker for mac too. We just need a small script that runs `docker run` with some preconfigured settings. Here is a [vagga issue for the topic, that has no feedback so far](https://github.com/tailhook/vagga/issues/269). We just need to figure out:

1. If we can keep `.vagga` folder on **host** system and how expensive it is (to allow IDEs accessing files inside the container) [*]
2. If (1) doesn't work figure out two more things:
  a) add something like `--volume=/work/.vagga:/vagga` 
  b) a way for vagga to copy `/usr/lib/python3.5/site-packages` outside of the container on each build 
3. Figure out how ports are published. Probably adding exposed ports to the metadata in vagga.yaml so this script can look at them (you only need ports you want to access from your host system, e.g. a browser, interconnection between processes/containers will work)

[*] Files in the project dir will definitely be accessible from a host filesystem. We only question files of the container filesystem, like system libraries, python packages...

Answers on few obvious questions:

1. *Will vagga in docker run slower than running by docker?* No, we just adding one layer of containers. Containers are cheap in linux. Like if you mount another hard-drive will it slow the system? No. 

2. *Will vagga in docker be less or more secure that docker?* Well, it isn't a useful question: we don't care about security of our own code on our own laptops :)

3. *Will there be any cross-platform issues for vagga? Previously vagga was run on linux only, so it was easier to make vagga.yaml*. I think they will be minimal if at all (mostly dealing with filesystems shared with a host).

4. *Does it requires too much OS X specific configuration?* I think it does not, probably (a) exposed ports and (b) exposed part of the filesystem (and maybe none of them). I think they might be useful for vagga on linux too: (a) we may isolate the network in vagga and only allow those ports (note we already have [pass-tcp-socket](http://vagga.readthedocs.io/en/latest/commands.html#opt-pass-tcp-socket) option), and (b) might be cool when we make [layers](http://vagga.readthedocs.io/en/latest/overlayfs.html) and deduplication (i.e. to disable optimizations for certain folders).

## What Are The Benefits?

Well, vagga is almost 2 years old (the first commit of bare readme file was at 28th June). So it already got some things. Here is what you are going to loose:

1. You need to define your own configuration format, reiterate, keep backward compatibility
2. You need to support documentation of this thing
3. You need all kinds of tutorials for all kinds of usage
4. You loose security on CI systems as described above
5. Vagga's tools for testing network resilience
6. And higher level build tools that vagga supports. If you think that relying on Dockerfile's makes your life easier, here is [a link that it's not](https://speakerdeck.com/garethr/the-dockerfile-explosion-and-the-need-for-higher-level-tools)
7. And the most important thing, you introduce a community fragmentation

## Isn't All This Insulting?

Well, I hope not. It's open source. We try to contribute and collaborate as much as possible to not to waste too much resources on duplicate efforts. Sometimes forks and rewrites are justified sometimes not. It happens that owners are just uninformed. And occasionally, projects join the effort again. Hopefully, we can make another successful case for that.

**Comment by vmagamedov** [comment]
It is very interesting task to make Vagga work on macOS, and to be honest, I didn't even try to make this happen. Nice idea to run Vagga in Docker.

I'm not so security-addicted as you. I really like that Vagga can work without root access to the host system, this is huge. But what if this feature is overrated? For me this is not obvious.

FYI, Pi is older than Vagga, first **working prototype** was committed at June 23, exactly two years ago:)

What I can see is that you are trying to show that Pi is an attempt just to copy some existing functionality, which obviously shouldn't have any sense. But:
- Pi doesn't try to reinvent containerization, it is using Docker (currently only Docker);
- Pi doesn't try to reinvent images management, it is using Docker Distribution;
- Pi doesn't try to reinvent "higher level build tools", it is using simple Dockerfile and will use Ansible optionally (working proof-of-concept already exists).

There is only one thing that Pi can duplicate - it is a DSL, used to describe environment and command-line interface using YAML syntax. And obviously yes, Vagga was the main source of inspiration here. But this is not enough to make Pi a tiny wrapper around Vagga, because Vagga isn't feature-full as Docker.

Just want to note one more time, that Pi is just getting a new shape, all functionality was already implemented in previous version of Pi (in-house) long time ago.

What is a purpose of doing this? To use Pi by myself on other projects and make it perfect for everyone who already is using Docker or trying to start using it. Pi is a really tiny project with zero stars on GitHub so far, and I don't understand how it can "introduce a community fragmentation", Docker is your enemy, not Pi:) And again, Pi is older than Vagga, how it can introduce a community fragmentation from the past? :)))

Maybe you would disagree, but I think that Pi makes Vagga better and Vagga also makes Pi better, just because of some sort of competition between them. And sure this is easier than trying to convince you regarding some questions about how things should work:)

**Comment by tailhook** [comment]
> Pi doesn't try to reinvent "higher level build tools",

Sure. For now it may be. But I'm almost sure you need to, and that's not my opinion, [here I'm repeating a link if you missed it](https://speakerdeck.com/garethr/the-dockerfile-explosion-and-the-need-for-higher-level-tools).

> Docker is your enemy

Docker isn't my enemy (I have no enemies in software, but nevermind). Docker is great that it makes lot of traction to containers, and that is a good thing. Just I think docker itself it's not good for my use cases.

> Pi is a really tiny project with zero stars on GitHub so far 
> [... snip ...]
> And again, Pi is older than Vagga, how it can introduce a community fragmentation from the past?

These statements do contradict each other. But anyway, let's stay technical.

> Maybe you would disagree, but I think that Pi makes Vagga better and Vagga also makes Pi better, just because of some sort of competition between them.

Competition is good. And collaboration is good too.

> And sure this is easier than trying to convince you regarding some questions about how things should work:)

Please, open up an issue on vagga's github on things that you think should be done other way. This is how open source works. I'm often wrong on many points and there are quite a few tickets closed in vagga's github that convinced me for some things.

**Comment by vmagamedov** [comment]
> Sure. For now it may be. But I'm almost sure you need to, and that's not my opinion, here I'm repeating a link if you missed it.

As I said before, it is possible to use [Ansible to provision Docker image](http://docs.ansible.com/ansible/intro_inventory.html#non-ssh-connection-types), and Pi also makes possible to build images hierarchy to solve maybe all problems mentioned [here](https://speakerdeck.com/garethr/the-dockerfile-explosion-and-the-need-for-higher-level-tools).

> Docker isn't my enemy (I have no enemies in software, but nevermind). Docker is great that it makes lot of traction to containers, and that is a good thing. Just I think docker itself it's not good for my use cases.

That was just a joke, nevermind. I think that Vagga is, first of all, a containerization tool, and it implements some Docker features in the other way, so naturally Vagga is alternative to Docker and is not alternative directly to Pi. Vagga is not compatible with Docker in any possible way, so the question is "Vagga or Docker?" and not "Vagga or Pi?".

Back in time when I had thoughts about how things should work, Vagga wasn't existed yet, so it is a bit late and Vagga already implements them.

**Comment by warik** [comment]
I think the simplest answer to this issue is that vagga just doesn't run on mac (for now?). You have even no mention about mac in installation docs and according to issue You've mentioned (and its opened state and very recent creation date) there is no solution for this or at least no one tried it.

And lets be honest, Your argument about vaggas' age is nonsense comparing to Pi just because, as was written previously, pi uses docker. So how old is docker? How much is docker community bigger over vaggas' one? How many big companies use docker comparing to vagga?

**Comment by AlexMost** [comment]
If Vagga is positioned as a better and more secure alternative to docker then the phrase "you need to install docker to run vagga on mac" sounds a little bit confusing for me as a user.
As for pi it would be really awesome if it could work with different types of containers (not sure if it is possible).

**Comment by tailhook** [comment]
> I think the simplest answer to this issue is that vagga just doesn't run on mac (for now?). You have even no mention about mac in installation docs and according to issue

Yes, documentation for running on mac needs to be added. There is [vagrant vagga](https://github.com/rrader/vagrant-vagga) by the way. But it's better if someone with the mac would add it.

> You've mentioned (and its opened state and very recent creation date) there is no solution for this or at least no one tried it.

There are multiple solutions. And the time needed to try vagga on mac and find out the best way for it is much smaller than rewriting everything.

> So how old is docker? How much is docker community bigger over vaggas' one?

It's like comparing with linux. How old is linux? vagga uses linux, right?

I mean if you used docker before, can you use pi out of the box? No, you need to learn pi's [configuration format](https://github.com/vmagamedov/pi/blob/master/pi.yaml) at least.

Do you need a documentation for pi, when there is a documentation for docker? Yes.

And so forth. So yes my comparison of pi with vagga makes more sense, than comparing with docker.

> If Vagga is positioned as a better and more secure alternative to docker then the phrase "you need to install docker to run vagga on mac" sounds a little bit confusing for me as a user.

I've already answered it. But let me repeat: We are interested in security on shared servers like CI. On workstation it less interesting. So yes, we will not run mac ox on CI servers.

> As for pi it would be really awesome if it could work with different types of containers (not sure if it is possible).

There are no different type of containers. The difference between vagga's and docker containers is just the commandline (or protocol) to run it. They are all linux containers. Even in docker for mac  there is a virtual machine running linux. And there are linux containers.

Okay, there are different types of containers: solaris zones and freebsd jails. It looks like pi doesn't work with them either.

**Comment by tailhook** [comment]
> > Pi doesn't try to reinvent "higher level build tools",
> [.. snip ..]

> As I said before, it is possible to use Ansible to provision Docker image, and Pi also makes possible to build images hierarchy to solve maybe all problems mentioned here.

So it **does** provide higher level build tools. Don't take me wrong. It's a good thing. But there is a learning curve and you need to keep up the documentation.

Also, using this approach you can't get rid of weirdness like the following:
```
RUN curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
    && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
    && rm "node-v$NODE_VERSION-linux-x64.tar.gz"
```

> But this is not enough to make Pi a tiny wrapper around Vagga, because Vagga isn't feature-full as Docker.

Can you elaborate? Vagga is more featured that docker for development environments.

> Vagga is not compatible with Docker in any possible way

There are a lot of ways vagga is compatible with docker:

* You can run vagga in docker
* You can `docker import` vagga's image
* etc.

It's all linux containers.

> I think that Vagga is, first of all, a containerization tool, and it implements some Docker features in the other way, 

Vagga is a tool to setup development environments in the first place. What system calls it uses and whether they are `socket()`, `read()` and `write()` (as pi), or `clone()` and `exec()` (as in vagga) is irrelevant to the discussion.

> so the question is "Vagga or Docker?" and not "Vagga or Pi?".

No there is no such question. The question is what tool to choose for building development environments. What tool is best suited for that. What features makes this tool great.

Vagga and pi are comparable to docker-compose. And the latter is super limited, right?

**Comment by vmagamedov** [comment]
> So it does provide higher level build tools. Don't take me wrong. It's a good thing. But there is a learning curve and you need to keep up the documentation.

Users will have to learn something "high-level" anyway, and Ansible is already exists with lots of documentation/tutorials/support and with modules of any kind for any task. Here Pi doesn't require users to learn something never existed before and Pi doesn't introduce "lock-in" of any kind, you are free to use Dockerfile or Playbook or something else in the future as you wish, with or without Pi.

> Also, using this approach you can't get rid of weirdness like the following: RUN curl...

How with Vagga I can get rid of this? Anyway, the only way to fix this, is to package software as deb/rpm/wheel/nix packages by yourself and host it from local repository. Or do you know the other way?

> Can you elaborate? Vagga is more featured that docker for development environments.

Ability to share builded images. Ability to run services as daemons. Ability to run code on remote machines, which gives ability to run seamlessly on macOS and on Linux.

> There are a lot of ways vagga is compatible with docker:

I apologize for the abstract definition. I meant another level of compatibility. Please remember that I'm was trying to compare Vagga vs Docker instead of your comparison of Vagga vs Pi. My point is that when you choose some containerization tool to develop and deploy software, you have two valid options:
- develop with Vagga and deploy with Lithos, Rocket, RunC, Systemd...
- develop with Docker and deploy with Docker, Lithos, Rocket, RunC, Systemd...

And there is no much sense in using Vagga to develop and Docker to share and deploy, I hope that this is clear for you too? Now I understand your point of view, that Vagga is more comparable to Pi than to Docker. But this is not relevant anyway, because when you choosing Vagga for development, you choose to forget everything about Docker and everything already written for Docker or with Docker support.

So for me and probably for other users the question sound like this: is Vagga worth of rejecting everything else with first-class Docker support? I'm talking about Docker Engine itself, Docker Distribute, Ansible, Mesos + Marathon/Aurora/..., Kubernetes, DC/OS, Docker for Mac, Docker for Windows...

And yes I know that I can `docker import`, but why if I can use Docker images as is and optionally `docker export` to deploy?

So now I will try to answer your question from the title. The answer is that Pi should exist at least as long as Docker exists. Or until someone will write a much superior solution to manage development environments across all platforms and there will be no sense in trying not to use it or trying to reimplement it. Pi is not a rewrite of Vagga from scratch, Pi is actually older than Vagga, so I don't feel myself guilty. Pi is trying to reuse as much as possible, and currently it is easier to reuse Docker than trying to improve Vagga and I don't see a lot of benefits in the future in trying to do this.

Please don't get me wrong, I understand that this is dumb not to admit that Vagga makes many things right and better than Docker, but currently I need a working tool to use and I don't want to feel less comfortable on macOS than users on Linux, because I'm using macOS for it's comfort and ease of use. And Pi/Docker gives this comfort to me and my users for almost 2 years now. It is not perfect, but does it's job well, or at minimum acceptable.

**Comment by EugeneN** [comment]
As Alan Kay uses to ask - would it stay relevant on an intergalactic scale? (This question is not intended to be answered literally, but instead to serve as an analysis instrument). What can we see from this perspective?:

Sure containerisation is the right way to do software, including OSes itself. But there is so much more to containers than Linux containers, Docker, Vagga or Pi offer. Containers should be composable, immutable, lightweight, versioned, universally accessible, location transparent, resource transparent, cryptographically verified and addressed - much like macOS's dmg filesystem snapshots - but covering all operational aspects. And most importantly - the very idea of OSes, user's shell, software distribution has to be rebuilt using these containers. 

Things like application state - running or not running, installed or not installed, local or cloud based - do not exist anymore in such a system. Things like security vulnerabilities and race conditions due to shared mutable state (fs, memory, etc) do not exist anymore, because there is no shared mutable state. Things like malware and viruses do not exist anymore. Things like local computer, local setup, different setup on different computers, notorious "configuration management" do not exist anymore - a user can import some given set of containers on any computer it has access to, or run this set in the cloud (there is "containers set" management, though, but it should be done using single proper typed functional declarative language, not a zoo of stringly-typed unix legacy tools and perl/python imperative "scripts"). Just like web-applications done right :-)

There are (only) immutable containers, users can "import" and use them deterministically - the same container version always provides the same functionality. Much like importing  libraries into a REPL.

I have described these ideas and api mockups [in my blog](http://eugenen.github.io/?ui=html#!blog/1db636e4abdb59a615d3)

From this perspective Pi has the rights to exist as Docker configuration management tool, Docker has the rights to exist as a (single?) cross-platform containers management tool and, most importantly, as a thing which has the potential to grow from primitive indirection layer to new higher order abstraction layer, Vagga has the rights to exist as niche solution, Linux-only 'chroot on steroids', which is basically an opposite idea to Docker - take a niche instead of growing to a new abstraction layer.

But all of them are not enough for what is required to fix the computing :-)

**Comment by tailhook** [comment]
> > Also, using this approach you can't get rid of weirdness like the following: RUN curl...

> How with Vagga I can get rid of this?

For that specific case there is a [Tar](http://vagga.readthedocs.io/en/latest/build_steps.html#step-Tar) command with is nice and clean.

There are more higher level commands in vagga which replace long and unreadable pipelines in dockerfile.

Additionally, with vagga you never need to `rm -rf /something` as a part of part of single multi-line command-line, because in there is no stacked layers (yes there are both upsides and downsides of the docker-like layers, but that's another topic)

> > Can you elaborate? Vagga is more featured that docker for development environments.

> Ability to share builded images.

There are multiple ways you can share images in vagga. But there are few definition of "sharing".

If by "sharing" you mean just uploading an image somewhere where user can download, there are:

1. `vagga _push_image` / `image-cache-url` which allows to upload a tar of an image to a location and fetch it back from there. It doesn't require any kind of registry on the other side. I.e. nginx with webdav module will work

2. You can use [container](http://vagga.readthedocs.io/en/latest/volumes.html#volume-Container) and whatever tool you like send and image. For example, we use `rsync` that way to deploy images to production effeciently.  I.e. a command `vagga deploy` validates some custom things and uses `rsync` to deploy images to production efficiently.

If by "sharing" you mean publishing it on docker hub. Then yes, we don't have a "hub". Technically you can use `image-cache-url` or maybe other things described 

But I honestly I don't think that downloading an arbitrary blob from an arbitrary user is a good idea. I believe that downloading yaml and building it on own infrastructure is safer. And what we do in vagga is we make the "build on own infrastructure" part easier and safer. For anybody never used vagga it's just `vagga _build image-name` so actually harder than `docker pull name/version`. And yes by "infrastructure" I mean you home laptop (or anything you like)

> Ability to run services as daemons.

Running daemons is not an invention of docker :). You can run any unix command in background as `command &`. There is a `jobs` command to manage them. Sure, you may run vagga command this way. (on newer linux systems there is `systemd-run` if you prefer manage daemons that way)

> Ability to run code on remote machines, which gives ability to run seamlessly on macOS and on Linux.

Running docker on remote machine is not "seamless". Your "--volume" works another way. Exposing ports works on other machines and so on.

You may run vagga on remote machine in same way seamlessly with "ssh vagga". For example, with "vagrant ssh vagga" or "vagrant vagga". The transport is different.

Do you think that it's better to use industry standard SSH-2 or *hacked* version of HTTP that docker uses to stream input/output? You don't care, right?

Yes "docker for mac" makes few things for you easier. But it's not a feature of remote execution. It's a specific set of hacks that docker for mac did. As I've described earlier we can reuse that hacks.

And yes we can make small OS X native "vagga" counterpart that does heavy-lifting and sends commands to xhyve vm. And yes it's smaller amount of work that rewrtiting everything. When I'm speaking about "smaller amount of work" I'm telling mostly about documentation, tutorial, debugging, and all that additional work that needs to be done. The code is just very small part of it (well I think there will be less code, too).


> Docker has the rights to exist as a (single?) cross-platform containers management tool and, most importantly, as a thing which has the potential to grow from primitive indirection layer to new higher order abstraction layer

Yes, it had that opportunity. But now the primitive layer is runc not docker. Yes docker uses it. Yes docker team helps to maintain it. But this example just shows that using lower level of abstractions make sense. And this is what vagga does too (if you wonder why vagga doesn't use runc, there are multiple reasons, but simplest is because vagga was before runc existed)

Another failure described in [devzen 92](http://devzen.ru/episode-0092/) starting with 1:44:00 (in russian). The story is that they tried docker 1.8 -- 1.10 and none of them worked. The 1.11 is still being evaluated by kubernetes team if it is a working solution. 

And so on. I mean Docker does great PR job, so that everyone thinks that docker is the only solution, but it's not.

> Vagga has the rights to exist as niche solution, Linux-only 'chroot on steroids',

runc is a chroot on steroids. Vagga is container build and versioning tool. It tries to do everything you need to setup development environment, including documenting command you need to run to start, test and deploy project.

> which is basically an opposite idea to Docker - take a niche instead of growing to a new abstraction layer.

So it's not an opposite idea to docker. It's a complement. Just like docker-compose, but with more features.

Again, it is not interesting to discuss system calls vagga uses. Like do you care if "tar" command that runs on linux uses `libarchive` like `bsdtar` (or just `tar` on bsd systems) or has it's own implementation of format? I don't care. What I care is that `bsdtar -xf` guesses compression format for me, but gnu `tar` don't.

----

At the and of the day, I recommend @vmagamedov to try vagga. You continuously show that you are misinformed for it's features. While it's fine to ask, your own experience is often a better thing.

**Comment by tailhook** [comment]
> I apologize for the abstract definition. I meant another level of compatibility.

I think you did not describe it. Yes you can develop with vagga and deploy in docker. Whether it makes sense is decribed below.

> And there is no much sense in using Vagga to develop and Docker to share and deploy, I hope that this is clear for you too?

No, it's not clear. And there are examples: [Here how you build "packages" using the new tool called habitat](https://www.habitat.sh/docs/create-packages-overview/). And yes they deploy with docker.

> is Vagga worth of rejecting everything else with first-class Docker support? I'm talking about Docker Engine itself, Docker Distribute, Ansible, Mesos + Marathon/Aurora/..., Kubernetes, DC/OS, Docker for Mac, Docker for Windows...

No. Vagga is irrelevant as described above.

> And yes I know that I can docker import, but why if I can use Docker images as is and optionally docker export to deploy?

Technically, you can do both ways it doesn't matter. Why would you export from vagga is stated in your next citation: 

> Please don't get me wrong, I understand that this is dumb not to admit that Vagga makes many things right and better than Docker

There are a lot of things that are about your estimation against my one. Both are more guess than something objective. I've just tried to show you links that prove few points from my messages.

**Comment by vmagamedov** [comment]
Discussion is ended with arguments about how Vagga is better than Docker. However it was said before that Vagga should be compared to Pi, and not to Docker. Don't see need to continue this discussion.

Closing this issue because @tailhook started https://github.com/tailhook/vagga-docker project to commandeer and answer his own question about how to run Vagga on macOS using tiny wrapper around Vagga.

Can't decide whether to close this project or not, it is still useful for me in some ways as a proof-of-concept.

**Comment by warik** [comment]
Please, do not close the project. I'm sure it will be used by reasonable amount of people.
